language: java
jdk: openjdk10
sudo: required
services:
- docker
jobs:
    include:
    - stage: asset ordering
      script: grep -v '^#' assets/src/main/resources/META-INF/services/bisq.asset.Asset | sort --check --dictionary-order --ignore-case
    - stage: build
      script: ./gradlew build
    - stage: integration
      env:
      - CUBE_LOGGER_ENABLE=true
      script:
          cd http-api;
          docker-compose build;
          ../gradlew testIntegration;
notifications:
    slack:
        on_success: change
        on_failure: always
        rooms:
        - secure: EzlqWTBuhb3FCfApjUXaShWgsWOVDwMXI7ISMiVBkcl2VFISYs/lc/7Qjr7rdy4iqQOQXMcUPHdwMUp0diX+GxiSjLARjUpKIvNOPswZWBL+3Z1h28jyOwtHRviZbM1EU0BZROrr+ODyTNz2lf+L1iXTkpSvk50o5JAnAkumsPw=
